"""add premium usage and remove ip

Revision ID: 76ffdc2c67e2
Revises: 977b0921b40b
Create Date: 2025-05-31 15:26:35.223779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ffdc2c67e2'
down_revision: Union[str, None] = '977b0921b40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_daily_usage', sa.Column('premium_interaction_input_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_daily_usage', sa.Column('premium_interaction_output_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_daily_usage', sa.Column('premium_interaction_queries', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_daily_usage', sa.Column('premium_summarization_input_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_daily_usage', sa.Column('premium_summarization_output_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_daily_usage', sa.Column('premium_summarization_queries', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_daily_usage', sa.Column('premium_translation_input_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_daily_usage', sa.Column('premium_translation_output_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_daily_usage', sa.Column('premium_translation_queries', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('users', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_daily_usage', 'premium_translation_queries')
    op.drop_column('user_daily_usage', 'premium_translation_output_tokens')
    op.drop_column('user_daily_usage', 'premium_translation_input_tokens')
    op.drop_column('user_daily_usage', 'premium_summarization_queries')
    op.drop_column('user_daily_usage', 'premium_summarization_output_tokens')
    op.drop_column('user_daily_usage', 'premium_summarization_input_tokens')
    op.drop_column('user_daily_usage', 'premium_interaction_queries')
    op.drop_column('user_daily_usage', 'premium_interaction_output_tokens')
    op.drop_column('user_daily_usage', 'premium_interaction_input_tokens')
    # ### end Alembic commands ###
